name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn
        
      - name: Build the project
        run: yarn build
        
      - name: Replace dev by prod dir
        uses: jacobtomlinson/gha-find-replace@v2  
        with:
          find: "src"
          replace: "dist"
          include: "index.js"
      
      - name: Replace dev files by prod files
        uses: jacobtomlinson/gha-find-replace@v2  
        with:
          find: "*.ts"
          replace: "*.js"
          include: "index.js"
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "test"
