name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn
        
      - name: Build the project
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "., !node_modules"
          target: "~/app/api_rentx"
          
      - name: Update API
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          command: |
            cd ~/app/api_rentx
            yarn
            ./node_modules/.bin/typeorm migration:run -d ./dist/shared/infra/typeorm/index.js
            pm2 restart rentx
